Part 1 of Tasks 3.4.
oksana-gorovaya/PHPandJS_Learning pull request #5
Opened 2019-06-10 09:14 UTC by oksana-gorovaya

2019-06-10 09:35 UTC, ulfheddin requested changes
Про Exception/Err критично. Функцію на три я б також розбив. Все інше - побажання.

2019-06-10 09:35 UTC, ulfheddin commented on decodeString.php
> +    var_dump("cannot read file");
var_dump не перериває виконання програми. Тобто ти скажеш користувачу що не змогла прочитати файл а потім все рівно спробуєш виконати весь інший код. Краще використовувати Exception для таких випадків.

2019-06-10 09:35 UTC, ulfheddin commented on decodeString.php
> +function splitInput($encodedFile, $pattern)
обидві функції просто приймають одинаковий патерн на вхід.
його можна передати параметром з дефолтним значенням. 
https://www.php.net/manual/ru/functions.arguments.php#functions.arguments.default

2019-06-10 09:35 UTC, ulfheddin commented on decodeString.php
> +    if ($numbers[0] === ","){
оця костиляка виглядатиме краще якщо ти її обернеш в окрему функцію хоча б і використаєш всередині функцію trim() щоб видалити коми з початку і кінця. Звісно це буде вже після implode() щоб працювати не з масивом. 
https://www.php.net/manual/ru/function.trim.php

2019-06-10 09:35 UTC, ulfheddin commented on decodeString.php
> +function separateCharacters($splitedInput, $pattern)
Ця функція робить:
1) Сегрегує літери і цифри
2) Видаляє першу кому
3) Наповнює новий масив даними

Sounds like три функції а то якась дуже жирна функція separateCharacters()

2019-06-10 09:35 UTC, ulfheddin commented on decodedString.js
> +    if (err) console.log(err);
та сама проблема що і в пхп
консоль лог не перериває виконання програми і під час помилки в тебе вилетить і повідомлення про помилку і повідомлення про успіх. Використовуй "throw err;"
https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_writefile_file_data_options_callback

2019-06-10 09:52 UTC, oksana-gorovaya commented on decodeString.php
> +    var_dump("cannot read file");
done.

2019-06-10 10:05 UTC, oksana-gorovaya commented on decodeString.php
> +function splitInput($encodedFile, $pattern)
done.

2019-06-11 06:49 UTC, oksana-gorovaya commented on decodeString.php
> +    if ($numbers[0] === ","){
done.

2019-06-11 14:40 UTC, oksana-gorovaya commented on decodeString.php
> +function separateCharacters($splitedInput, $pattern)
done.

2019-06-11 14:40 UTC, oksana-gorovaya commented on decodedString.js
> +    if (err) console.log(err);
все дан.

2019-06-11 15:27 UTC, ulfheddin commented on decodeString.php
> +            } else{
(minor) you can just drop whole else block and it will change nothing. "Continue" is useless if it is last line of a cycle.

2019-06-11 15:30 UTC, ulfheddin approved these changes
красава

2019-06-12 08:19 UTC, ulfheddin approved these changes

2019-06-18 18:53 UTC, merged